erDiagram
    CUSTOMER ||--o{ ORDERS : places
    ORDERS  ||--|{ ORDER_LINE : contains
    PRODUCT ||--o{ ORDER_LINE : appears_in

    CUSTOMER {
        int customer_id PK
        string first_name
        string last_name
        string address
        string email UK
    }

    ORDERS {
        int order_id PK
        int(NN) customer_id FK
        date(NN) order_date
    }

    PRODUCT {
        int(NN) product_id PK
        string name
        int(NN) price
        string availability_status
    }

    ORDER_LINE {
        int orderline_id PK
        int(NN) order_id FK
        int(NN) product_id FK
        int(NN)(CHECK) quantity
    }
